import type { Metadata } from "next";

import "../globals.css";

import Navbar from "@/components/Navbar";

import { Spotlight } from "@/components/ui/Spotlight";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`overflow-hidden bg-black antialiased`}
      >
        <Spotlight
        className="-top-40 left-0 md:left-[20%] md:-top-20"
        fill="#393BB2"
        />
         <Spotlight
        className="-top-40 left-0 md:left-[100%] md:-top-20"
        fill="#E2CBFF"
        />
       
        <Navbar/>
        {children}
        
      </body>
    </html>
  );
}
